### PR TITLE
fix(api): expand `~` in process cwd paths

### LINKED ISSUE #194: Fix `~` usage in process cwd
for example
```typescript
await glide.process.execute("ls", [], { cwd: "~/.dotfiles" })
```
will result in these error logs in the console
```
DataCloneError: Exception object could not be cloned. [subprocess_worker_common.js:224:15](resource://gre/modules/subprocess/subprocess_worker_common.js)

Glide: Object { errorCode: undefined } [browser-excmds.mjs:112:25](chrome://glide/content/browser-excmds.mjs)
```
I'm not sure why this is happening yet but it should just be expanded to the home directory.

### PR DESCRIPTION
**Pull request by suveshmoza**
Created a helper function `expand_tilde` which replaces `~` and `~/` from `opts.cwd` with the `home_dir`  inside `process.spawn`

Fixes #194

### CODE REVIEW

File: src/glide/browser/base/content/test/process/browser_process.ts [hunk 1]
```diff
@@ -235,6 +235,56 @@ add_task(async function test_cwd_option() {
...
+});
+
+add_task(async function test_cwd_tilde_slash_expansion() {
+  await reload_config(function() {
+    glide.keymaps.set("normal", "~", async () => {
+      const test_subdir = "test_tilde_expansion";
+      const expected_path = glide.path.join(glide.path.home_dir, test_subdir);
+
+      if (!(await glide.fs.exists(expected_path))) {
+        await glide.fs.mkdir(expected_path);
```
Comment (RobertCraigie) [inline src/glide/browser/base/content/test/process/browser_process.ts]: Mutating the user home directory isn't ideal. It looks like you can override the home directory to a temp directory with this
```ts
const { AddonTestUtils } = ChromeUtils.importESModule("resource://testing-common/AddonTestUtils.sys.mjs"); 

// ...

const tmpdir = Services.dirsvc.get("TmpD", Ci.nsIFile);
tmpdir.append("test-home-" + Date.now());
tmpdir.create(Ci.nsIFile.DIRECTORY_TYPE, 0o755);
AddonTestUtils.registerDirectory('Home', tmpdir);
```

File: src/glide/browser/base/content/test/process/browser_process.ts [hunk 2]
```diff
@@ -235,6 +235,56 @@ add_task(async function test_cwd_option() {
...
+      const absolute_path = glide.path.home_dir;
+      const proc = await glide.process.spawn("pwd", [], { cwd: absolute_path });
+      const output = (await Array.fromAsync(proc.stdout.values())).join("").trim();
+      glide.g.value = output;
+    });
+  });
+
+  await glide.keys.send("~");
+  await waiter(() => glide.g.value).is(glide.path.home_dir, "absolute paths without ~ should remain unchanged");
+});
```
Comment (RobertCraigie) [inline src/glide/browser/base/content/test/process/browser_process.ts]: nit: I think this test doesn't actually assert that there is no expansion?

I think a more meaningful test would be that passing the cwd as something like `"/absolute/path/with/~/in/the/middle"` doesn't expand the `~` in the middle.

**Review by RobertCraigie — APPROVED** [review]
Thanks!
